---
- group: name={{ vg_vault_group }} state=present

- user: name={{ vg_vault_user }} comment="Very Good Vault User" group={{ vg_vault_group }} home={{ vg_vault_home }} state=present

- file: path={{ vg_vault_home }} state=directory owner={{ vg_vault_user }} group={{ vg_vault_group }}

- file: path=/var/log/{{ vg_vault_user }} state=directory owner={{ vg_vault_user }} group={{ vg_vault_group }}
- file: path={{ vg_vault_newrelic_home }} state=directory owner={{ vg_vault_user }} group={{ vg_vault_group }}

- name: Download newrelic jar
  get_url: url={{ vg_vault_newrelic_url }} dest=/tmp/newrelic.zip mode=0444

- apt: update_cache=yes name=unzip state=present

- name: Extract new relic
  unarchive: src=/tmp/newrelic.zip dest=/opt/ copy=no

- name: Install newrelic config
  template: dest={{ vg_vault_home }}newrelic.yml src=newrelic.yml.j2 owner={{ vg_vault_user }} group={{ vg_vault_group }}
