---
# tasks file for verygood.vault
- include: common.yml
  tags:
    - vault

- include: http.yml
  tags:
    - vault
    - vault-http
  when: vg_vault_install_http

- include: sftp.yml
  tags:
    - vault
    - vault-sftp
  when: vg_vault_install_sftp
