---

- name: Create config dir
  file: path=/etc/verygood/ state=directory owner={{ vg_vault_user }} group={{ vg_vault_group }} recurse=yes

- name: Copy config to {{ vg_vault_config_sftp }}
  template: dest={{ vg_vault_config_sftp }} backup=yes src=vault-sftp.config.yml.j2 owner={{ vg_vault_user }} group={{ vg_vault_group }} mode=0644
  notify:
    - restart vault sftp

- name: Copy hostkey to config dir
  copy: dest={{ vg_vault_config_dir }}vault-sftp.key src=vault-sftp.key owner={{ vg_vault_user }} group={{ vg_vault_group }} mode=0440
  notify:
    - restart vault sftp

- name: Create runit dir
  file: path=/etc/service/vault-sftp/log state=directory owner={{ vg_vault_user }} group={{ vg_vault_group }} recurse=yes

- name: Install runit config
  template: dest=/etc/service/vault-sftp/run src=runit/run.j2 owner={{ vg_vault_user }} group={{ vg_vault_group }}

- name: Install runit config
  template: dest=/etc/service/vault-sftp/log/run src=runit/log/run.j2 owner={{ vg_vault_user }} group={{ vg_vault_group }}

- name: Install Supervisor
  apt: name=supervisor state=present

- name: Supervisor config
  template: dest=/etc/supervisor/conf.d/vault-sftp.conf src=vault-sftp.supervisor.j2 owner={{ vg_vault_user }} group={{ vg_vault_group }}
  notify:
    - start supervisor service
    - reread supervisor service
    - update supervisor service

- name: Install Vault binary
  get_url: url={{ vg_vault_sftp_binary_url }} dest={{ vg_vault_sftp_binary }} sha256sum={{ vg_vault_sftp_binary_hash }}
  notify:
    - restart vault sftp

- name: Vault Healthy
  copy: dest={{ vg_vault_file_health_check.file_path }} content="Very Good to go" owner={{ vg_vault_user }} group={{ vg_vault_group }}

- name: Wait for vault-sftp to come up
  wait_for: host={{ vg_vault_sftp_bind }} port={{ vg_vault_sftp_port }} delay=10 state=drained
