---
# handlers file for verygood.vault
- name: restart vault http
  command: supervisorctl restart vault-http

- name: restart vault sftp
  command: supervisorctl restart vault-sftp

- name: start vault
  service: name=vault state=started

- name: start supervisor service
  service: name=supervisor state=started

- name: restart supervisor service
  service: name=supervisor state=restarted

- name: restart monit
  service: name=monit state=restarted

- name: reload logrotate
  command: logrotate -s /var/lib/logrotate.status /etc/logrotate.conf
